# Generated by Django 4.2.2 on 2023-06-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'extent',
                'verbose_name_plural': 'extents',
            },
        ),
        migrations.CreateModel(
            name='Naming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'naming',
                'verbose_name_plural': 'namings',
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadnumber', models.IntegerField()),
                ('frompoint', models.FloatField()),
                ('topoint', models.FloatField()),
                ('settlement', models.CharField(max_length=50)),
                ('fromwhen', models.DateField()),
                ('towhen', models.DateField()),
                ('speed', models.IntegerField()),
                ('extent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_2012_majus_idegen.extent')),
                ('naming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_2012_majus_idegen.naming')),
            ],
            options={
                'verbose_name': 'restriction',
                'verbose_name_plural': 'restrictions',
            },
        ),
    ]
